services:
  dvwa:
    image: vulnerables/web-dvwa
    ports:
      - "127.0.0.1:8080:80"
    restart: unless-stopped

  bwapp:
    image: raesene/bwapp
    ports:
      - "127.0.0.1:8081:80"
    restart: unless-stopped

  vampi:
    image: erev0s/vampi
    ports:
      - "127.0.0.1:5000:5000"
    restart: unless-stopped
