version: "3.8"
services:
  juice-shop:
    image: bkimminich/juice-shop:latest
    container_name: juice-shop
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
